const colors = require('tailwindcss/colors');
const spacing = require('./config/spacing');
const variants = require('./config/variants');
module.exports = {
	prefix: '',
	//presets: [],
	purge: [],
	darkMode: false, // or 'media' or 'class'
	theme: {
		extend: {},
		screens: {
			sm: '768px',
			md: '1024px',
			lg: '1280px',
			xl: '1536px'
		},
		colors: {
			transparent: 'transparent',
			current: 'currentColor',
			white: colors.white,
			red: colors.red
		},
		...spacing,
	},
	variants: {
		...variants,
		extend: {},
	},
	plugins: [
		require('./plugins/base/base'),
		/* require('./plugins/components/btn') */
	],
	corePlugins: {
		preflight: true,
		container: true,
		accessibility: false,
		alignContent: false,
		alignItems: false,
		alignSelf: false,
		animation: false,
		appearance: false,
		backgroundAttachment: false,
		backgroundClip: false,
		backgroundColor: false,
		backgroundImage: false,
		backgroundOpacity: false,
		backgroundPosition: false,
		backgroundRepeat: false,
		backgroundSize: false,
		borderCollapse: false,
		borderColor: false,
		borderOpacity: false,
		borderRadius: false,
		borderStyle: false,
		borderWidth: false,
		boxShadow: false,
		boxSizing: false,
		clear: false,
		cursor: false,
		display: false,
		divideColor: false,
		divideOpacity: false,
		divideStyle: false,
		divideWidth: false,
		fill: false,
		flex: false,
		flexDirection: false,
		flexGrow: false,
		flexShrink: false,
		flexWrap: false,
		float: false,
		fontFamily: true,
		fontSize: true,
		fontSmoothing: false,
		fontStyle: true,
		fontVariantNumeric: false,
		fontWeight: true,
		gap: false,
		gradientColorStops: false,
		gridAutoColumns: false,
		gridAutoFlow: false,
		gridAutoRows: false,
		gridColumn: false,
		gridColumnEnd: false,
		gridColumnStart: false,
		gridRow: false,
		gridRowEnd: false,
		gridRowStart: false,
		gridTemplateColumns: false,
		gridTemplateRows: false,
		height: false,
		inset: false,
		justifyContent: false,
		justifyItems: false,
		justifySelf: false,
		letterSpacing: false,
		lineHeight: false,
		listStylePosition: false,
		listStyleType: false,
		margin: true,
		maxHeight: false,
		maxWidth: false,
		minHeight: false,
		minWidth: false,
		objectFit: false,
		objectPosition: false,
		opacity: false,
		order: false,
		outline: false,
		overflow: false,
		overscrollBehavior: false,
		padding: true,
		placeContent: false,
		placeholderColor: false,
		placeholderOpacity: false,
		placeItems: false,
		placeSelf: false,
		pointerEvents: false,
		position: false,
		resize: false,
		ringColor: false,
		ringOffsetColor: false,
		ringOffsetWidth: false,
		ringOpacity: false,
		ringWidth: false,
		rotate: false,
		scale: false,
		skew: false,
		space: false,
		stroke: false,
		strokeWidth: false,
		tableLayout: false,
		textAlign: true,
		textColor: true,
		textDecoration: false,
		textOpacity: false,
		textOverflow: false,
		textTransform: false,
		transform: false,
		transformOrigin: false,
		transitionDelay: false,
		transitionDuration: false,
		transitionProperty: false,
		transitionTimingFunction: false,
		translate: false,
		userSelect: true,
		verticalAlign: false,
		visibility: false,
		whitespace: false,
		width: false,
		wordBreak: false,
		zIndex: false,
	}
}